<a href="https://colab.research.google.com/github/shilpapanniru/ShilpaReddyDS/blob/main/CSGO.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Counter-Strike (CS)** is a popular series of tactical first-person shooter (FPS) video games that have been enjoyed by gamers worldwide for many years. The series originated as a modification for the popular game Half-Life and quickly gained its own dedicated following. Here's an overview of Counter-Strike:

**Gameplay Overview:**

Counter-Strike is primarily a multiplayer game where two teams, the Counter-Terrorists (CTs) and the Terrorists (Ts), compete against each other.

The objective of each round varies based on the game mode, but the primary goals include:

**Counter-Terrorists:** Prevent the Terrorists from achieving their objectives, such as defusing a bomb or rescuing hostages.

**Terrorists:** Achieve their objectives, which may include planting a bomb at a designated site or holding hostages.
Rounds are relatively short, typically lasting a few minutes, and players have only one life per round. When a player is eliminated, they must wait until the next round to respawn.

**Key Features:**

**Weapons:** Players can purchase and use a wide variety of firearms, grenades, and equipment. The choice of weaponry is an essential strategic element in the game.

**Economy:** Players earn in-game money based on their performance in the previous rounds. Money is used to buy weapons and equipment for the next round.

**Maps:** Counter-Strike features a range of maps, each with its own layout and objectives. Popular maps include Dust II, Mirage, Inferno, and more.

**Teamwork:** Successful gameplay in Counter-Strike heavily relies on teamwork, communication, and strategy. Players often coordinate their actions with their teammates to achieve objectives.

**Competitive Play:** Counter-Strike is well-known for its competitive scene, with professional esports tournaments held worldwide.

**Popular Game Modes:**

**Bomb Defusal (de_):** In this mode, Terrorists attempt to plant a bomb at one of the designated bomb sites, while Counter-Terrorists aim to prevent the bomb from being planted or defuse it if it's planted.

**Hostage Rescue (cs_):** In hostage rescue mode, Counter-Terrorists must rescue hostages held by the Terrorists, while the Terrorists aim to prevent the rescues.

**Arms Race:** A fast-paced mode where players cycle through a series of weapons, aiming to be the first to get a kill with each weapon.

**Deathmatch:** A mode where players respawn quickly and aim to get as many kills as possible within a set time limit.

**Wingman:** A 2v2 competitive mode with smaller maps and shorter rounds.

Counter-Strike has evolved over the years with different versions, including Counter-Strike 1.6, Counter-Strike: Source, and Counter-Strike: Global Offensive (CS:GO), which is the most recent and widely played installment as of my last knowledge update in September 2021.

CS:GO is known for its competitive gameplay, professional esports scene, and ongoing updates that have kept the game relevant and enjoyable for players worldwide. It remains a cornerstone of the first-person shooter genre.



In [ ]:
# DataSet:-https://drive.google.com/file/d/16L9RgJtDycmgWsmZz48aVUKyk9l5ty1H/view?usp=drive_link

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df=pd.read_csv('/content/csgo_round_snapshots.csv')

In [ ]:
df

time_left  ct_score  t_score       map  bomb_planted  ct_health  \
0          175.00       0.0      0.0  de_dust2         False      500.0   
1          156.03       0.0      0.0  de_dust2         False      500.0   
2           96.03       0.0      0.0  de_dust2         False      391.0   
3           76.03       0.0      0.0  de_dust2         False      391.0   
4          174.97       1.0      0.0  de_dust2         False      500.0   
...           ...       ...      ...       ...           ...        ...   
122405      15.41      11.0     14.0  de_train          True      200.0   
122406     174.93      11.0     15.0  de_train         False      500.0   
122407     114.93      11.0     15.0  de_train         False      500.0   
122408      94.93      11.0     15.0  de_train         False      500.0   
122409      74.93      11.0     15.0  de_train         False      375.0   

        t_health  ct_armor  t_armor  ct_money  ...  t_grenade_flashbang  \
0          500.0       0.0      0.0    4000.0  ...                  0.0   
1          500.0     400.0    300.0     600.0  ...                  0.0   
2          400.0     294.0    200.0     750.0  ...                  0.0   
3          400.0     294.0    200.0     750.0  ...                  0.0   
4          500.0     192.0      0.0   18350.0  ...                  0.0   
...          ...       ...      ...       ...  ...                  ...   
122405     242.0     195.0    359.0     100.0  ...                  2.0   
122406     500.0      95.0    175.0   11500.0  ...                  2.0   
122407     500.0     495.0    475.0    1200.0  ...                  4.0   
122408     500.0     495.0    475.0    1200.0  ...                  5.0   
122409     479.0     395.0    466.0    1100.0  ...                  3.0   

        ct_grenade_smokegrenade  t_grenade_smokegrenade  \
0                           0.0                     0.0   
1                           0.0                     2.0   
2                           0.0                     2.0   
3                           0.0                     0.0   
4                           0.0                     0.0   
...                         ...                     ...   
122405                      1.0                     1.0   
122406                      1.0                     0.0   
122407                      3.0                     5.0   
122408                      0.0                     3.0   
122409                      0.0                     2.0   

        ct_grenade_incendiarygrenade  t_grenade_incendiarygrenade  \
0                                0.0                          0.0   
1                                0.0                          0.0   
2                                0.0                          0.0   
3                                0.0                          0.0   
4                                0.0                          0.0   
...                              ...                          ...   
122405                           0.0                          0.0   
122406                           0.0                          0.0   
122407                           1.0                          0.0   
122408                           0.0                          0.0   
122409                           0.0                          0.0   

        ct_grenade_molotovgrenade  t_grenade_molotovgrenade  \
0                             0.0                       0.0   
1                             0.0                       0.0   
2                             0.0                       0.0   
3                             0.0                       0.0   
4                             0.0                       0.0   
...                           ...                       ...   
122405                        0.0                       0.0   
122406                        0.0                       0.0   
122407                        0.0                       5.0   
122408                        0.0     

In [ ]:
df.shape

(122410, 97)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122410 entries, 0 to 122409
Data columns (total 97 columns):
 #   Column                        Non-Null Count   Dtype  
---  ------                        --------------   -----  
 0   time_left                     122410 non-null  float64
 1   ct_score                      122410 non-null  float64
 2   t_score                       122410 non-null  float64
 3   map                           122410 non-null  object 
 4   bomb_planted                  122410 non-null  bool   
 5   ct_health                     122410 non-null  float64
 6   t_health                      122410 non-null  float64
 7   ct_armor                      122410 non-null  float64
 8   t_armor                       122410 non-null  float64
 9   ct_money                      122410 non-null  float64
 10  t_money                       122410 non-null  float64
 11  ct_helmets                    122410 non-null  float64
 12  t_helmets                     122410 non-nul

In [ ]:
df.isnull().sum().sum()

np.int64(0)

In [ ]:
df.duplicated().sum()

np.int64(4962)

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le=LabelEncoder()
for col in df.columns:
  if((df[col].dtype=='object') | (df[col].dtype=='bool')):
    df[col]=le.fit_transform(df[col])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 117448 entries, 0 to 122409
Data columns (total 97 columns):
 #   Column                        Non-Null Count   Dtype  
---  ------                        --------------   -----  
 0   time_left                     117448 non-null  float64
 1   ct_score                      117448 non-null  float64
 2   t_score                       117448 non-null  float64
 3   map                           117448 non-null  int64  
 4   bomb_planted                  117448 non-null  int64  
 5   ct_health                     117448 non-null  float64
 6   t_health                      117448 non-null  float64
 7   ct_armor                      117448 non-null  float64
 8   t_armor                       117448 non-null  float64
 9   ct_money                      117448 non-null  float64
 10  t_money                       117448 non-null  float64
 11  ct_helmets                    117448 non-null  float64
 12  t_helmets                     117448 non-null  fl

In [ ]:
#x and y
x=df.drop('round_winner',axis=1)
y=df['round_winner']

In [ ]:
x.shape

(117448, 96)

In [ ]:
y

0         0
1         0
2         0
3         0
4         0
         ..
122405    1
122406    1
122407    1
122408    1
122409    1
Name: round_winner, Length: 117448, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20)

In [ ]:
x_train.shape

(93958, 96)

In [ ]:
x_test.shape

(23490, 96)

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sc=StandardScaler()

In [ ]:
x_train_scale=sc.fit_transform(x_train)
x_test_scale=sc.transform(x_test)

In [ ]:
#weightage/coeff= importance of a column  #3x1, 5x2 high # 3x1 , -4x2
#y=w1x1+w2x2+w3x3+.....w96x96
#n_compenets =1
#w1,w2,w3...w96--> 20

In [ ]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [ ]:
LDA=LinearDiscriminantAnalysis()

In [ ]:
LDA.fit(x_train_scale,y_train)

LinearDiscriminantAnalysis()

In [ ]:
len(LDA.coef_[0])

96

In [ ]:
lda_coef=LDA.coef_

In [ ]:
lda_coef=lda_coef.flatten()
lda_coef

array([ 1.44338629e-01, -1.20886316e-02,  1.63430670e-02, -8.89352985e-02,
        2.54610172e-01, -4.61849303e-01,  3.23117701e-01, -5.99714466e-01,
        6.43647122e-01, -2.17117624e-01,  1.67166762e-01,  5.97660684e-03,
        8.02820392e-02, -2.58334097e-02, -1.89780121e-01,  3.69414687e-01,
       -1.79913212e-01,  6.03036299e-01, -1.98784959e-01,  3.13356476e-02,
       -3.05035369e-01,  2.45748185e-01,  2.05641585e-15,  1.69442096e-05,
        1.33130726e-02, -9.41289658e-04, -3.59504950e-03,  1.79712192e-02,
       -1.39479372e-01,  4.64996627e-02,  2.08759349e-15,  1.72140283e-02,
       -4.93079020e-02,  1.41905786e-01,  2.34593656e-02, -1.34820900e-01,
        1.14727717e-02,  8.92092543e-16, -9.72948570e-02,  4.90930399e-02,
       -4.60713951e-01,  1.08469098e-01, -1.55107598e-02,  1.02403575e-01,
       -1.79311390e-02,  8.10322017e-03, -1.68064379e-02,  3.40149324e-02,
        9.89851960e-03, -6.80708983e-03, -1.07441614e-01,  3.50235753e-02,
       -1.72255249e-15, -

In [ ]:
lda_coef=np.exp(np.abs(lda_coef))
lda_coef

array([1.15527525, 1.01216199, 1.01647735, 1.09300993, 1.28995866,
       1.58700613, 1.38142794, 1.8215986 , 1.9034102 , 1.24249024,
       1.18195135, 1.0059945 , 1.08359264, 1.02616998, 1.20898374,
       1.44688748, 1.19711346, 1.82765971, 1.21991961, 1.03183178,
       1.35667299, 1.27857757, 1.        , 1.00001694, 1.01340209,
       1.00094173, 1.00360152, 1.01813367, 1.14967509, 1.04759773,
       1.        , 1.01736304, 1.05054377, 1.15246806, 1.0237367 ,
       1.14433182, 1.01153884, 1.        , 1.10218531, 1.05031807,
       1.58520534, 1.11457047, 1.01563168, 1.10783047, 1.01809287,
       1.00813614, 1.01694846, 1.03460006, 1.00994767, 1.00683031,
       1.11342585, 1.03564412, 1.        , 1.0077805 , 1.01985515,
       1.02050254, 1.02085596, 1.01556148, 1.        , 1.0066544 ,
       1.        , 1.01555516, 1.00335434, 1.01246915, 1.23311265,
       1.74575394, 1.0886793 , 1.02600535, 1.04498479, 1.09539541,
       1.02136748, 1.00557691, 1.02154548, 1.00374589, 1.03589

In [ ]:
feature_names=x_train.columns
feature_names

Index(['time_left', 'ct_score', 't_score', 'map', 'bomb_planted', 'ct_health',
       't_health', 'ct_armor', 't_armor', 'ct_money', 't_money', 'ct_helmets',
       't_helmets', 'ct_defuse_kits', 'ct_players_alive', 't_players_alive',
       'ct_weapon_ak47', 't_weapon_ak47', 'ct_weapon_aug', 't_weapon_aug',
       'ct_weapon_awp', 't_weapon_awp', 'ct_weapon_bizon', 't_weapon_bizon',
       'ct_weapon_cz75auto', 't_weapon_cz75auto', 'ct_weapon_elite',
       't_weapon_elite', 'ct_weapon_famas', 't_weapon_famas',
       'ct_weapon_g3sg1', 't_weapon_g3sg1', 'ct_weapon_galilar',
       't_weapon_galilar', 'ct_weapon_glock', 't_weapon_glock',
       'ct_weapon_m249', 't_weapon_m249', 'ct_weapon_m4a1s', 't_weapon_m4a1s',
       'ct_weapon_m4a4', 't_weapon_m4a4', 'ct_weapon_mac10', 't_weapon_mac10',
       'ct_weapon_mag7', 't_weapon_mag7', 'ct_weapon_mp5sd', 't_weapon_mp5sd',
       'ct_weapon_mp7', 't_weapon_mp7', 'ct_weapon_mp9', 't_weapon_mp9',
       'ct_weapon_negev', 't_weapon_negev',

In [ ]:
df_col_imp=pd.DataFrame({'Feature':feature_names,'importance':lda_coef})

In [ ]:
df_col_imp

Feature  importance
0                     time_left    1.155275
1                      ct_score    1.012162
2                       t_score    1.016477
3                           map    1.093010
4                  bomb_planted    1.289959
..                          ...         ...
91  t_grenade_incendiarygrenade    1.012565
92    ct_grenade_molotovgrenade    1.005092
93     t_grenade_molotovgrenade    1.108033
94      ct_grenade_decoygrenade    1.003275
95       t_grenade_decoygrenade    1.021779

[96 rows x 2 columns]

In [ ]:
#20->
# 1.sort based uopn imporatance col
# 2.we will slicce top 20 columns

# n_large()
top20=df_col_imp.nlargest(20,'importance')
top20

Feature  importance
8                  t_armor    1.903410
17           t_weapon_ak47    1.827660
7                 ct_armor    1.821599
65          t_weapon_sg553    1.745754
5                ct_health    1.587006
40          ct_weapon_m4a4    1.585205
15         t_players_alive    1.446887
6                 t_health    1.381428
20           ct_weapon_awp    1.356673
4             bomb_planted    1.289959
21            t_weapon_awp    1.278578
89  t_grenade_smokegrenade    1.261668
9                 ct_money    1.242490
64         ct_weapon_sg553    1.233113
18           ct_weapon_aug    1.219920
14        ct_players_alive    1.208984
87     t_grenade_flashbang    1.203763
16          ct_weapon_ak47    1.197113
10                 t_money    1.181951
0                time_left    1.155275

In [ ]:
top20.index

Index([8, 17, 7, 65, 5, 40, 15, 6, 20, 4, 21, 89, 9, 64, 18, 14, 87, 16, 10,
       0],
      dtype='int64')

In [ ]:
imp_ind=top20.index
imp_ind

Index([8, 17, 7, 65, 5, 40, 15, 6, 20, 4, 21, 89, 9, 64, 18, 14, 87, 16, 10,
       0],
      dtype='int64')

In [ ]:
x_train_scale[:,[8,17,7,65,40]] #

array([[-1.16523752, -0.20986646,  0.00767899],
       [-0.01495769, -0.94137827, -0.10384339],
       [-0.15874267, -0.94137827, -1.86472313],
       ...,
       [ 1.04905116, -0.94137827, -0.13906098],
       [-0.18174827,  0.52164536, -1.86472313],
       [-1.74037744, -0.94137827, -0.10384339]])

In [ ]:
x_train_scale[:,imp_ind]  #imp_ind=[8, 17, 7, 65, 5, 40, 15, 6, 20, 4, 21, 89, 9, 64, 18, 14, 87, 16, 10,0]

array([[-1.16523752, -0.20986646,  0.00767899, ...,  1.21224835,
        -0.91435185, -1.27288381],
       [-0.01495769, -0.94137827, -0.10384339, ..., -0.47854702,
        -0.82854836,  1.41752627],
       [-0.15874267, -0.94137827, -1.86472313, ..., -0.47854702,
         0.58108041,  1.51093415],
       ...,
       [ 1.04905116, -0.94137827, -0.13906098, ..., -0.47854702,
         0.12754767,  0.38308568],
       [-0.18174827,  0.52164536, -1.86472313, ..., -0.47854702,
         0.96106729,  1.41639861],
       [-1.74037744, -0.94137827, -0.10384339, ..., -0.47854702,
         4.22159992,  1.50980649]])

In [ ]:
x_train_lda=x_train_scale[:,imp_ind]
x_train_lda.shape

(93958, 20)

In [ ]:
x_test_lda=x_test_scale[:,imp_ind]
x_test_lda.shape

(23490, 20)

In [ ]:
# model building
# model:-LR,DTC,RFC

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
model_lr=LogisticRegression()

In [ ]:
model_lr.fit(x_train_lda,y_train)

LogisticRegression()

In [ ]:
y_pred_lr=model_lr.predict(x_test_lda)

In [ ]:
from sklearn.metrics import *

In [ ]:
accuracy_score(y_pred_lr,y_test)*100

75.38101319710515

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
model_dt=DecisionTreeClassifier()

In [ ]:
model_dt.fit(x_train_lda,y_train)

DecisionTreeClassifier()

In [ ]:
y_pred_dt=model_dt.predict(x_test_lda)

In [ ]:
accuracy_score(y_pred_dt,y_test)*100

78.77820349084716

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
model_rf=RandomForestClassifier(n_estimators=100)

In [ ]:
model_rf.fit(x_train_lda,y_train)


RandomForestClassifier()

In [ ]:
y_pred_rf=model_rf.predict(x_test_lda)

In [ ]:
accuracy_score(y_pred_rf,y_test)*100

83.78458918688804

In [ ]:
# RF (84)  > DT (79)  >LR (75)

In [ ]:
# [20] ->new_rec-> model_rf.predict(new_rec)

In [ ]:
df['round_winner'].value_counts()

round_winner
1    59941
0    57507
Name: count, dtype: int64

In [ ]:
# GridSearchCV () -> {max_depth,n-esptimator,criterion}  ->
#SMOTE